# Generated by Django 4.1.7 on 2023-02-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Названия задания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус задания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('image', models.ImageField(upload_to='', verbose_name='Добавление фото')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('created_at', models.DateField(verbose_name='Время создания пользователя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
        ),
    ]
