# Generated by Django 4.1.7 on 2023-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='О нас'),
            preserve_default=False,
        ),
    ]
