# Generated by Django 4.1.7 on 2023-02-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_about_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название комнаты')),
                ('roomimage', models.ImageField(upload_to='roomimgs/', verbose_name='Фото комнат')),
                ('description', models.TextField(verbose_name='Описание комнаты')),
                ('price', models.CharField(max_length=12)),
            ],
        ),
    ]
