# Generated by Django 4.1.7 on 2023-02-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена за день'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ваше имя')),
                ('lastname', models.CharField(max_length=255, verbose_name='Ваша фамилия')),
                ('phone', models.IntegerField(verbose_name='Ваш номер')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.rooms')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
